language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - unixodbc-dev
script:
- pip install nose
- nosetests
deploy:
  provider: codedeploy
  access_key_id: AKIAJZVOGJPNL2FRTLBQ
  bucket: S3 Bucket
  revision_type: github
  application: "isiscb-develop-app"
  deployment_group: "isiscb-develop-deploymentgroup"
  secret_access_key:
      secure: "l4PjRpXgDMlkkRA+DaM0bZCS22pnsiivDaQvtI3GY1+ckNOP1MH89aL/Aeer4dUxg/bUDsCLKPpQq52C4X2EY9FQhNTJvg76QJFs5TzVaU1XL8Qhphv8tDhtMRw8oc2iLakXqFO5u5BX3cViCIaPKIfNHuWG+MsKMnZLF55gqnGWCfIDXiARZdlQV2aZXHOtxnbE3V9pwpdIQUGmIOtgKnKaOPIU5sK5JXQvnS3VMLFtXx8EMOONF9HQyyyymdRGr/4QjERIyAq/guHlMGBv7dPYbcoF0PCWn6AnWb4KFOIm9XhAPnQnKD7tWhR1NzaxS7d51evpzcnFgtf6ZF2eT/1tcnrVyyUkXKinAhznCD6IUCkd2SEXIyzMpBfpzr1y75v6HyLRKyop1944mhnuPOcZlwf6TPLj7Oi6EGZrLzdHWZ/BhmnrC1+fz4RpxyO7RQfCF1nueJKCyFbhmV0Ay572kYDM+P9Q//P26fdW2V+vUspqaQKFS7o6dMd81duop92VKo5fIkJU1PsJvwDNA9UJps4IhVz6cN43ld6vCIhXtdJQwrvl4jg7xWd1ohzY1m+730ivAazXrsY1uvQCWVpVbGc49XT8GweTR3S6HnI//KJfSSf2MO+dhgfKdZqymYLWtTCJIAirBfsflCasyugvf+YlA9xpjZAd+mFd3ug="
