language: python
python:
- '2.7'
env:
  global:
    - DJANGO_SETTINGS_MODULE=isiscb.local_settings
script:
- pip install nose
- cd isiscb
- git clone http://github.com/ubernostrum/django-registration.git --depth 2
- python manage.py migrate
- python -Wi manage.py test
deploy:
  - provider: codedeploy
    access_key_id: AKIAIVNDMWM77W3N2KTA
    region: us-west-2
    bucket: S3 Bucket
    revision_type: github
    application: "isiscb-develop-app"
    deployment_group: "isiscb-develop-deploymentgroup"
    secret_access_key:
      secure: "osQ5jCPZsn/RasLViriEYTNElAwIKFkkG5fmurDeeV/PrtUuk/u4Bi5mXDw5LLp8RCggEQAExTiAcJKvERUGkNrkRB4p7ExeoTzEf8YaBfwwXotZ4YtdiEt/iIa53aIAZz2pVLpDeJ3pK1OyK/jQPLE5yCwHEDLZVWMNtjXE1fmPVsQWX5p+5VK5ntEeZjMunZBgZFa6B2uvGNJFVhK5ymFREkoJT3lqH4cavD1ddf5lP1wjf0YtAqmuVaRZzyOIN/zdPMEsj5G38na7p/d89kCfSr6X9+0EMOso3l0MXztKoBiY9x0REV9GH8UGoJV2pltljw/CNRcE2BZg7x4SamZRmeLNx2409Xk5JAQ2AQ7/rCQweCEmIPCLZMmMz99i5UzsZ8Y/pgNBRLS9qwugXssvQd7ypJnce0iRueCndX1C2Al4XnomTwlHWamwvtC/CszMlT1zFLvi0DiUOyX0dYm1MzpBDPB/Gy8T7JJ9zRigZ9QzqapDi6mZ2D2Dt7rT0CQL6kdZIy7upFReEs5pNaNn64hlK5PVTa9dn7hO8O2T6J9gvbTi0xXhefPGaHnOUtQeOtJBe/xStbz8RKSn7XIXt9VYtgiJ4RfW2YAiofnGhnwQYy5HKJgbrPGC1uCHAeNpR5uq5AQEVbET8lghuoqm97lw1VtbVMYuB17AWnQ="
    on:
      branch: develop
  - provider: elasticbeanstalk
    access_key_id: AKIAI3SRBWU3O3X5S7CQ
    secret_access_key:
      secure: "PBNXD4sae1vLFKg2oI6LnHtJflHFhhrSnT6GEw7p7j+XDKyiW+wt9gnljEMyZBBif1Yfsj/13QIxOVj6GyE75CGTvuknhY4spiMkQa9abgHPAQFlmv4PNb4lnvie4121kmrvgF05bjgFFcCotrYzONm9Aum/170gQzeKEsiD4LIeUQ8+7zgMXf/SMiGeij9OpeIYsHpJSKJi1vYUFJB11r3r0yYw+3LUqMrW/58mkEB4ZpycprstluwKS9jaYxXKk8AqHHp2IxPEjNAfyoI+j4G6efcj501HOMVIiXdbDVENf46WmFMYXQelqcEByNukYT6hdLZX+00hws5cnjo37UhhLG3BvlJU2dFLPhCYVaJO1lpXQqUUKqFSvY4PdXVQf4mnQJHVFx0jqvsJWCsHGMBXHPkhphblESBMy5Wiu9n0VKRW5X69/Vk4KPoUU8PGfV4KyvP3xMtb0R979/Poz2cRPQShp1E7Vx5GHseLXlWNPkFQZ42DbEKnV7U8Pt577/W3hgt3SV0uSnqYZcaADarV30q9ho0wDzqLNfak3NU6aBE+wYUgkLyWROsYpE5Ja0QEmqnVleyYIQ3aiZaOHF1URi82ZH3cbYAZuFfuvOBiKVDYYNFFtOWqvS4J6cvxhkgT2Gx3/Dqh6Of6Y4RVuulU7dJ5UBuc/ObTzE7+tR4="
    region: us-west-2
    app: isiscb
    env: isiscb-staging
    bucket_name: elasticbeanstalk-us-west-2-655333410217
    on:
      repo: isiscb
      branch: master
