language: python
python:
- '2.7'
env:
  global:
    - DJANGO_SETTINGS_MODULE=isiscb.local_settings
script:
- pip install nose
- cd isiscb
- git clone http://github.com/ubernostrum/django-registration.git --depth 2
- python manage.py migrate
- python -Wi manage.py test
deploy:
  - provider: codedeploy
    access_key_id: AKIAIVNDMWM77W3N2KTA
    region: us-west-2
    bucket: S3 Bucket
    revision_type: github
    application: "isiscb-develop-app"
    deployment_group: "isiscb-develop-deploymentgroup"
    secret_access_key:
      secure: "osQ5jCPZsn/RasLViriEYTNElAwIKFkkG5fmurDeeV/PrtUuk/u4Bi5mXDw5LLp8RCggEQAExTiAcJKvERUGkNrkRB4p7ExeoTzEf8YaBfwwXotZ4YtdiEt/iIa53aIAZz2pVLpDeJ3pK1OyK/jQPLE5yCwHEDLZVWMNtjXE1fmPVsQWX5p+5VK5ntEeZjMunZBgZFa6B2uvGNJFVhK5ymFREkoJT3lqH4cavD1ddf5lP1wjf0YtAqmuVaRZzyOIN/zdPMEsj5G38na7p/d89kCfSr6X9+0EMOso3l0MXztKoBiY9x0REV9GH8UGoJV2pltljw/CNRcE2BZg7x4SamZRmeLNx2409Xk5JAQ2AQ7/rCQweCEmIPCLZMmMz99i5UzsZ8Y/pgNBRLS9qwugXssvQd7ypJnce0iRueCndX1C2Al4XnomTwlHWamwvtC/CszMlT1zFLvi0DiUOyX0dYm1MzpBDPB/Gy8T7JJ9zRigZ9QzqapDi6mZ2D2Dt7rT0CQL6kdZIy7upFReEs5pNaNn64hlK5PVTa9dn7hO8O2T6J9gvbTi0xXhefPGaHnOUtQeOtJBe/xStbz8RKSn7XIXt9VYtgiJ4RfW2YAiofnGhnwQYy5HKJgbrPGC1uCHAeNpR5uq5AQEVbET8lghuoqm97lw1VtbVMYuB17AWnQ="
    on:
      branch: develop
  - provider: elasticbeanstalk
    access_key_id: AKIAI3SRBWU3O3X5S7CQ
    secret_access_key:
      secure: "J7fe8r7zTRHk8qYW+NfXzFIFzq+Kuz+P3H66nhlvV/avB8JpeZxqQjg+RwgHfmFdGk1vFDabTvm1NR2ZDQXByejB9XqECp3/SXVj78gMbt2ibiqblQ60AzwadWyjm0LDrM2Gt4oe2RgsODc1YctGQT8WS7ng8ErRn34uMZr6kOiJHllFxLDRVv34tHXIBdEoDzU656JJcqAxVrHsVGanWMr1j9ACx9wyNLfck/P2dFjNj/u+QwiApi9jhMxc83ix5RBL7LwOv0OEgIppBb7Fn1dePvmuzt2+Uxd7R+ChwWNgtwNkDQoz79g8Od9H4exfKvFyfknV7HRLiToG91mJv574WTWCsbV7W8pCeyKDCcZSqkbHmBj87Tp2tsueSPdGz2XhgNepUcOOGS5RFI4t1cpjDnLa7iow9WZJHrdqym+gs1Vqx+cyd85o4Sys+Me1co0kVOmzy/f8aPXXwrhqL9GYhnRfsRnaWwbqylTyB/6PVv54sEWeA8RbewPhriF3MeUAh9gCY/KM5cW18UTQz/ykt1E1UCXwAy/g8err3oRHBp3V+u8Irn+N71VkxjY5ekEW6Gcd2qeTT2f68Xg/9TZvbO6OkSF/6MbbdSN0dq/r6HixBwZU2s7IMJAvp1U7Gr+0DkVmZtMMmlAIbFigwhFaiZsbEQN+SGs/35COCco="
    region: us-west-2
    app: isiscb
    env: isiscb-staging
    bucket_name: elasticbeanstalk-us-west-2-655333410217
    on:
      repo: upconsulting/IsisCB
      branch: master
