version: 0.0
os: linux
files:
  - source: isiscb
    destination: /home/ec2-user/isiscb/isiscb
  - source: awsdeploy
    destination: /home/ec2-user/isiscb/awsdeploy
  - source: requirements.txt
    destination: /home/ec2-user/isiscb
  - source: awsdeploy/supervisor.conf
    destination: /etc/supervisor/conf.d
hooks:
  ApplicationStop:
    - location: awsdeploy/ApplicationStop.sh
      timeout: 1000
      runas: ec2-user
  BeforeInstall:
    - location: awsdeploy/BeforeInstall.sh
      timeout: 1000
      runas: root
  AfterInstall:
    - location: awsdeploy/AfterInstall.sh
      timeout: 1000
      runas: ec2-user
  # ApplicationStart:
  #   - location: awsdeploy/ApplicationStart.sh
  #     timeout: 1000
  #     runas: ec2-user
